### ISSUE TITLE
Add support for vue.js (vue single file component)

### ISSUE THREAD

**Issue by uniquejava** [fivethree-team/vscode-ionic-snippets#19]
Hi. Are there any settings for this plugin.
I'd like to use it in `*.vue` file, ionic 4 officially supports react and vue.js.

**Comment by marcjulian** [comment]
Hi, I haven't used vue yet. This exentsion supports snippets for the following files: `html`, `typescript`, `scss`.

Which file types are used with vuejs and which do you like to be supported by this extension?
Do you like to create a PR? I can point out how to get started.

**Comment by ghaddon** [comment]
Would like to see support for Vue.js "vue" files supported.

**Comment by marcjulian** [comment]
@ghaddon I am not a Vue.js developer. Please create a PR for vue support. If you need help I can point out how to get started. 

Which file types do you need to support for Vue.js?

**Comment by ghaddon** [comment]
Hello Marc,
I need help with opening a PR.Just let me know what I need to do to get started.
Thanks,Gary


   On Monday, April 8, 2019, 3:47:54 PM MST, Marc <notifications@github.com> wrote: 
 
 
@ghaddon I am not a Vue.js developer. Please create a PR for vue support. If you need help I can point out how to get started.

Which file types do you need to support for Vue.js?

**Comment by marcjulian** [comment]
Too get started you need to add the snippet type for the language you like to support to the `package.json`. 

Currently this extension support html, scss and typescript files.
```
"contributes": {
        "snippets": [
            {
                "language": "html",
                "path": "./snippets/html.json"
            },
            {
                "language": "scss",
                "path": "./snippets/scss.json"
            },
            {
                "language": "typescript",
                "path": "./snippets/typescript.json"
            }
        ]
},
```

For vue, you might need to add `vue` language support or even more, depending on the file types used in vue. Create for each snippet a JSON file inside of snippets, for example `snippets/vue.json`.
Add this to the snippets array inside of the package.json:
```
{
  "language": "vue",
  "path": "./snippets/vue.json"
}
```

**Comment by ghaddon** [comment]
Marc,
Do you want me to fork the library and make changes to support Vue?
Gary
   On Monday, April 8, 2019, 4:06:45 PM MST, Marc <notifications@github.com> wrote: 
 
 
Too get started you need to add the snippet type for the language you like to support to the package.json.

Currently this extension support html, scss and typescript files.
"contributes": {
        "snippets": [
            {
                "language": "html",
                "path": "./snippets/html.json"
            },
            {
                "language": "scss",
                "path": "./snippets/scss.json"
            },
            {
                "language": "typescript",
                "path": "./snippets/typescript.json"
            }
        ]
},

For vue, you might need to add vue language support or even more, depending on the file types used in vue. Create for each snippet a JSON file inside of snippets, for example snippets/vue.json.
Add this to the snippets array inside of the package.json:
{
  "language": "vue",
  "path": "./snippets/vue.json"
}

**Comment by marcjulian** [comment]
Yes please fork this repo and create a Pull Request :)

**Comment by marcjulian** [comment]
One more think, press `F5` in VSCode to `Debug: Start`. This will open a new VSCode instance where the new snippets should be available.

**Comment by marcjulian** [comment]
@uniquejava @ghaddon  please install the latest version `1.3.0` and give me feedback to the first vue support
