### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by bramji06** [fivethree-team/vscode-ionic-snippets#24]
Issue Type: <b>Bug</b>

Some time is working and some time not working. 

Extension version: 1.4.0
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (0.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by marcjulian** [comment]
Thanks for your issue. The snippet selection sometimes works and sometimes doesn't work in VSCode? I haven't experienced it yet. Do you have other snippet extension installed? If so do they have the same behavior as the Ionic snippets?
