### ISSUE TITLE
Unable to install this extension in my VS code editor

### ISSUE THREAD

**Issue by andaralex** [fivethree-team/vscode-ionic-snippets#27]
I am facing this issue while installing this **Ionic Snippets** extension in vs code

**Error:**
Unable to install because, the extension 'fivethree.vscode-ionic-snippets' compatible with current version '1.19.3' of VS Code is not found.

Could anyone can help me to resolve this issue or install this extension in my vs code editor.

**Comment by marcjulian** [comment]
@andaralex this extension needs a VS Code version of `1.26.0` or higher. The current version is `1.44.0`.  Please update your VS Code to the latest or atleast `1.26.0`.

**Comment by marcjulian** [comment]
I am closing this issue. Please let me know if upgrading VSCode helped you.
