### ISSUE TITLE
Ionic 6

### ISSUE THREAD

**Issue by mbnoimi** [fivethree-team/vscode-ionic-snippets#31]
May you please support current version of ionic.

```
$ ionic --version
6.12.4
```

**Comment by marcjulian** [comment]
@mbnoimi Ionic 6 has not been released yet. Latest version is [5.5.3](https://github.com/ionic-team/ionic-framework/releases). What do you mean by supporting the new version? Is anything missing? If so please provide a pull request 👍

**Comment by rgbaman** [comment]
Ionic 6 framework has now been released, are there any plans to update this? It's a lifesaver!

**Comment by marcjulian** [comment]
@rgbaman do you want to add a PR for ionic 6?
